export const Chargers = [
  {
    name: "Expressway Charging - Alpha Station",
    id: "a001",
    address: "Connaught Place, Delhi",
    distance: "2.1",
    distance_metrics: "km",
    latitude: "28.6304",
    longitude: "77.2177",
    connector_types: ["lvl1dc-2", "lvl2dc-1", "normalac-1"],
  },
  {
    name: "Green Power Hub - Beta",
    id: "b002",
    address: "Saket, New Delhi",
    distance: "5.8",
    distance_metrics: "km",
    latitude: "28.5215",
    longitude: "77.2041",
    connector_types: ["lvl2dc-3", "normalac-2"],
  },
  {
    name: "Charge Point - Gamma",
    id: "c003",
    address: "Gurugram, Haryana",
    distance: "15.2",
    distance_metrics: "km",
    latitude: "28.4595",
    longitude: "77.0266",
    connector_types: ["lvl1dc-1", "lvl2dc-2"],
  },
  {
    name: "Electro Fuel - Delta",
    id: "d004",
    address: "Noida, Uttar Pradesh",
    distance: "18.5",
    distance_metrics: "km",
    latitude: "28.5355",
    longitude: "77.3910",
    connector_types: ["normalac-4"],
  },
  {
    name: "Rapid Charge - Epsilon",
    id: "e005",
    address: "Dwarka, New Delhi",
    distance: "22.1",
    distance_metrics: "km",
    latitude: "28.6132",
    longitude: "77.0387",
    connector_types: ["lvl1dc-2", "lvl2dc-2", "normalac-1"],
  },
  {
    name: "Power Up Station - Zeta",
    id: "f006",
    address: "Faridabad, Haryana",
    distance: "30.7",
    distance_metrics: "km",
    latitude: "28.4085",
    longitude: "77.3178",
    connector_types: ["lvl2dc-1", "normalac-3"],
  },
  {
    name: "EV Connect - Eta",
    id: "g007",
    address: "Ghaziabad, Uttar Pradesh",
    distance: "25.3",
    distance_metrics: "km",
    latitude: "28.6700",
    longitude: "77.4500",
    connector_types: ["lvl1dc-3"],
  },
  {
    name: "Bolt Energy - Theta",
    id: "h008",
    address: "South Extension, Delhi",
    distance: "7.9",
    distance_metrics: "km",
    latitude: "28.5729",
    longitude: "77.2116",
    connector_types: ["lvl2dc-2", "normalac-2"],
  },
  {
    name: "ChargeWell - Iota",
    id: "i009",
    address: "Karol Bagh, Delhi",
    distance: "4.1",
    distance_metrics: "km",
    latitude: "28.6500",
    longitude: "77.2000",
    connector_types: ["lvl1dc-1", "normalac-1"],
  },
  {
    name: "Plug Point - Kappa",
    id: "j010",
    address: "Vasant Kunj, Delhi",
    distance: "12.5",
    distance_metrics: "km",
    latitude: "28.5500",
    longitude: "77.1600",
    connector_types: ["lvl2dc-3"],
  },
  {
    name: "AmpUp - Lambda",
    id: "k011",
    address: "Greater Noida, Uttar Pradesh",
    distance: "35.0",
    distance_metrics: "km",
    latitude: "28.4700",
    longitude: "77.5000",
    connector_types: ["lvl1dc-2", "normalac-2"],
  },
  {
    name: "Volta Charging - Mu",
    id: "l012",
    address: "Rohini, Delhi",
    distance: "10.3",
    distance_metrics: "km",
    latitude: "28.7000",
    longitude: "77.1200",
    connector_types: ["lvl2dc-1", "normalac-1"],
  },
  {
    name: "E-Fill Station - Nu",
    id: "m013",
    address: "Laxmi Nagar, Delhi",
    distance: "9.6",
    distance_metrics: "km",
    latitude: "28.6400",
    longitude: "77.2500",
    connector_types: ["lvl1dc-1", "lvl2dc-1"],
  },
  {
    name: "Charge Zone - Xi",
    id: "n014",
    address: "Pitampura, Delhi",
    distance: "13.8",
    distance_metrics: "km",
    latitude: "28.7200",
    longitude: "77.1500",
    connector_types: ["normalac-3"],
  },
  {
    name: "Power Pod - Omicron",
    id: "o015",
    address: "Janakpuri, Delhi",
    distance: "16.1",
    distance_metrics: "km",
    latitude: "28.6300",
    longitude: "77.1000",
    connector_types: ["lvl2dc-2"],
  },
];
